// filepath: 
name: Xcode - Build and Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # 添加手动触发选项

jobs:
  build:
    name: Build, analyse and package
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
      
      # 构建应用步骤
      - name: Archive App
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          # 构建应用程序并导出
          xcodebuild -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -configuration Release -derivedDataPath build
          
          # 保存APP名称供后续使用
          APP_PATH=$(find ./build -name "*.app" -type d | head -n 1)
          APP_NAME=$(basename "$APP_PATH" .app)
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          
      - name: Create DMG
        run: |
          # 安装create-dmg工具
          brew install create-dmg
          
          # 找到构建的.app文件
          APP_PATH=$(find ./build -name "*.app" -type d | head -n 1)
          APP_NAME=$(basename "$APP_PATH" .app)
          
          # 创建DMG文件
          create-dmg \
            --volname "$APP_NAME" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "$APP_NAME.app" 200 190 \
            --hide-extension "$APP_NAME.app" \
            --app-drop-link 600 185 \
            "$APP_NAME.dmg" \
            "$APP_PATH"
            
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4  # 升级到 v4 版本
        with:
          name: app-dmg
          path: "*.dmg"
          
      # 创建GitHub Release，并添加安全提示说明
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch' || contains(github.ref, 'master')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
          files: "*.dmg"
          body: |
            # ${{ env.APP_NAME }} v${{ github.run_number }}
            
            ## 安装说明
            
            由于应用未经过苹果签名和公证，首次安装时可能会遇到安全警告。按照以下步骤安装:
            
            1. 右键点击应用程序，选择"打开"
            2. 在弹出的对话框中，再次点击"打开"
            
            ### 或者启用"允许任何来源"选项:
            
            1. 打开系统偏好设置 > 安全性与隐私 > 通用
            2. 尝试运行应用后，会出现"已阻止应用运行"的提示和"仍要打开"的选项
            3. 点击"仍要打开"
            
            构建时间: ${{ github.event.repository.updated_at }}
            提交: ${{ github.sha }}
